<?php $deviceStateText = ['registered'=>'Registrované','registering'=>'Zapisuje se','pending'=>'Čeká','incomplete'=>'Neúplné','blocked'=>'Zakázané'][$device['registration_state']] ?? $device['registration_state']; ?>
<section class="page-intro device-detail-intro"><div><a class="back-link" href="<?= e(url('/devices')) ?>">← Registrovaná zařízení</a><p><?= e($device['person_name'] ?: 'Bez držitele') ?> · <span class="mono"><?= e($device['mac_address']) ?></span></p></div><div class="page-actions"><span class="badge <?= e($device['registration_state']) ?>"><i></i><?= e($deviceStateText) ?></span><?php if ((int) $device['online'] === 1): ?><span class="badge registered"><i></i>Online</span><?php endif; ?><?php if ($auth->isAdmin()): ?><form method="post" action="<?= e(url('/devices/repair')) ?>" data-confirm="Obnovit konfiguraci Access Listu, DHCP a Simple Queue podle WiFi Manageru?"><?= csrf_field() ?><input type="hidden" name="device_id" value="<?= (int) $device['id'] ?>"><button class="button subtle" type="submit"><?= icon('refresh') ?> Opravit konfiguraci</button></form><?php endif; ?></div></section>

<?php if (is_private_mac($device['mac_address'])): ?><div class="info-banner warning"><?= icon('alert') ?><div><strong>Zařízení používá soukromou MAC adresu</strong><p>Pokud telefon začne adresu pravidelně měnit, bude se hlásit jako nové zařízení. V nastavení této Wi‑Fi je vhodná pevná soukromá adresa.</p></div></div><?php endif; ?>

<section class="flow-summary-grid device-facts"><article><span>Statická IP</span><strong class="mono"><?= e($device['current_ip'] ?: '—') ?></strong></article><article><span>CAPsMAN</span><strong><?= ($device['capsman_type'] ?? 'wifi') === 'legacy' ? 'Starý' : 'Nový WiFi' ?></strong></article><article><span>Registrováno</span><strong><?= e(format_datetime($device['registered_at'])) ?></strong></article><article><span>Relací</span><strong><?= count($sessions) ?></strong></article></section>

<section class="panel"><header class="panel-header"><div><span class="panel-kicker">HISTORIE PŘIPOJENÍ</span><h2>Připojení a odpojení</h2><p>Syslogové události doplněné kontrolou registrační tabulky.</p></div></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Čas</th><th>Událost</th><th>Síť</th><th>Přístupový bod</th><th>Důvod / zdroj</th></tr></thead><tbody>
<?php if ($events === []): ?><tr class="empty-row"><td colspan="5"><strong>Zatím nejsou uložené žádné události.</strong></td></tr><?php endif; ?>
<?php foreach ($events as $event): ?><tr><td class="mono"><?= e(format_datetime($event['occurred_at'])) ?></td><td><span class="badge <?= $event['event_type']==='disconnected'?'offline':'registered' ?>"><i></i><?= e(['connected'=>'Připojeno','disconnected'=>'Odpojeno','roamed'=>'Přechod mezi AP'][$event['event_type']] ?? $event['event_type']) ?></span></td><td><?= e($event['ssid'] ?: '—') ?></td><td><?= e($event['access_point_name'] ?: ($event['interface_name'] ?: '—')) ?></td><td><?= e($event['reason'] ?: '—') ?><small class="subline"><?= e(strtoupper($event['source'])) ?></small></td></tr><?php endforeach; ?>
</tbody></table></div></section>

<form method="get" action="<?= e(url('/devices/detail')) ?>" class="panel archive-filters"><input type="hidden" name="id" value="<?= (int) $device['id'] ?>"><header class="panel-header"><div><span class="panel-kicker">PROVOZNÍ DATA</span><h2>Síťový provoz zařízení</h2><p>Data jsou přiřazena podle IP adresy platné v daném období.</p></div><button class="button primary" type="submit"><?= icon('search') ?> Načíst provoz</button></header><div class="archive-filter-grid"><label><span>Od</span><input type="datetime-local" name="from" value="<?= e($from) ?>" required></label><label><span>Do</span><input type="datetime-local" name="to" value="<?= e($to) ?>" required></label><label class="span-2"><span>Historická IP adresa</span><select name="ip"><?php foreach ($ipAssignments as $assignment): ?><option value="<?= e($assignment['ip_address']) ?>" <?= $selectedIp===$assignment['ip_address']?'selected':'' ?>><?= e($assignment['ip_address']) ?> · od <?= e(format_datetime($assignment['valid_from'])) ?></option><?php endforeach; ?></select></label></div></form>

<?php if ($flowError): ?><div class="toast error"><?= icon('alert') ?><span><?= e($flowError) ?></span></div><?php endif; ?>
<section class="flow-summary-grid"><article><span>Toky</span><strong><?= number_format((int) $flows['summary']['flows'],0,',',' ') ?></strong></article><article><span>Přenesená data</span><strong><?= e(format_bytes($flows['summary']['bytes'])) ?></strong></article><article><span>Pakety</span><strong><?= number_format((int) $flows['summary']['packets'],0,',',' ') ?></strong></article><article><span>Protistrany</span><strong><?= number_format((int) $flows['summary']['endpoints'],0,',',' ') ?></strong></article></section>
<section class="panel archive-results"><header class="panel-header"><div><span class="panel-kicker">NETFLOW / IPFIX</span><h2>Poslední síťové toky</h2></div></header><div class="table-wrap"><table class="data-table flow-table"><thead><tr><th>Začátek</th><th>Zdroj</th><th></th><th>Cíl</th><th>Protokol</th><th>Objem</th></tr></thead><tbody>
<?php if ($flows['rows'] === []): ?><tr class="empty-row"><td colspan="6"><strong>Pro zvolené období nejsou dostupná provozní data.</strong><small>Zkontrolujte stav sběru IPFIX nebo vyberte jinou IP adresu.</small></td></tr><?php endif; ?>
<?php foreach ($flows['rows'] as $row): ?><tr><td class="mono"><?= e(format_datetime($row['first_at'])) ?></td><td class="mono"><?= e($row['source_ip']) ?><?= $row['source_port']?':'.(int)$row['source_port']:'' ?></td><td class="flow-arrow"><?= icon('arrow-right') ?></td><td class="mono"><?= e($row['destination_ip']) ?><?= $row['destination_port']?':'.(int)$row['destination_port']:'' ?></td><td><span class="protocol-pill"><?= e($row['protocol'] ?: '—') ?></span></td><td><strong><?= e(format_bytes($row['bytes'])) ?></strong><small class="subline"><?= number_format((int)$row['packets'],0,',',' ') ?> paketů</small></td></tr><?php endforeach; ?>
</tbody></table></div></section>
