<form method="post" action="<?= e(url('/settings')) ?>" class="settings-page">
<?= csrf_field() ?>
<section class="panel settings-section"><header class="panel-header"><div><span class="panel-kicker">ROUTEROS API</span><h2>Připojení k MikroTiku</h2><p>API komunikace není šifrovaná. Přístup na port 8728 omezte pouze na adresu tohoto serveru; heslo je v SQLite uložené šifrovaně.</p></div><span class="badge <?= e($router['status']) ?>"><i></i><?= e(['online'=>'Online','offline'=>'Nedostupný','error'=>'Chyba','unconfigured'=>'Nenastaveno'][$router['status']] ?? $router['status']) ?></span></header>
<div class="form-grid settings-grid"><label class="span-2"><span>Název routeru</span><input name="name" value="<?= e($router['name']) ?>" required></label><label><span>IP adresa / hostname</span><input name="host" value="<?= e($router['host']) ?>" required class="mono"></label><label><span>API port</span><input type="number" name="port" value="<?= (int)$router['port'] ?>" min="1" max="65535" required></label><label><span>Uživatelské jméno</span><input name="username" value="<?= e($router['username']) ?>" required autocomplete="off"></label><label><span>Heslo API</span><input type="password" name="password" autocomplete="new-password" placeholder="<?= $router['id']?'Ponechat beze změny':'Zadejte heslo' ?>"></label></div>
<?php if ($router['last_error']): ?><div class="form-alert error"><?= icon('alert') ?> <?= e($router['last_error']) ?></div><?php endif; ?>
</section>
<section class="panel settings-section"><header class="panel-header"><div><span class="panel-kicker">REGISTRACE ZAŘÍZENÍ</span><h2>Výchozí pravidla</h2><p>Hodnoty lze při jednotlivé registraci upravit.</p></div></header><div class="form-grid settings-grid"><label><span>Registrační VLAN</span><input type="number" name="registration_vlan_id" value="<?= e($settings['registration_vlan_id']) ?>" min="1" max="4094"></label><label><span>Provozní VLAN</span><input type="number" name="approved_vlan_id" value="<?= e($settings['approved_vlan_id']) ?>" min="1" max="4094"></label><label><span>Registrační DHCP server</span><input name="registration_dhcp_server" value="<?= e($settings['registration_dhcp_server']) ?>" class="mono"></label><label><span>Provozní DHCP server</span><input name="approved_dhcp_server" value="<?= e($settings['approved_dhcp_server']) ?>" class="mono"></label><label><span>Začátek statického rozsahu</span><input name="static_ip_start" value="<?= e($settings['static_ip_start']) ?>" class="mono"></label><label><span>Konec statického rozsahu</span><input name="static_ip_end" value="<?= e($settings['static_ip_end']) ?>" class="mono"></label><label><span>Výchozí rychlost download</span><input name="default_rate_down" value="<?= e($settings['default_rate_down']) ?>"></label><label><span>Výchozí rychlost upload</span><input name="default_rate_up" value="<?= e($settings['default_rate_up']) ?>"></label><label><span>Zařízení na jednoho držitele</span><input type="number" name="max_devices_per_person" value="<?= (int)$settings['max_devices_per_person'] ?>" min="1" max="20"></label></div></section>
<div class="settings-actions"><button class="button subtle" type="submit" name="action" value="save"><?= icon('settings') ?> Uložit nastavení</button><button class="button primary" type="submit" name="action" value="test"><?= icon('refresh') ?> Uložit a otestovat spojení</button></div>
</form>
